spring.application.name=demo

# Supabase Database Configuration (Based on your provided URL)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.rgydjdoyphzkxuacwbbv
spring.datasource.password=Haipro08012004@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
